name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run sample script
        run: echo CI process started!

  lint:
    needs: [java-version]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      # Gradle v8.0.0 requires java JDK v17
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload Lint HTML test report
        uses: actions/upload-artifact@v2
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html

  unit-tests:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run gradlew test
        run: ./gradlew test

      - name: Upload Unit Test report
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report
          path: app/build/reports/test/testDebugUnitTest/

